services:
  frontend:
    image: garvg4278/shipforge-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: garvg4278/shipforge-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://shipforge:shipforge_dev@db:5432/shipforge
      JWT_SECRET: supersecretkey   # ✅ REQUIRED FIX
      NODE_ENV: production

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: shipforge
      POSTGRES_PASSWORD: shipforge_dev
      POSTGRES_DB: shipforge
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: